name: Publish

on: 
  push:
    tags: ["*"]

jobs:

  publish:
    runs-on: ubuntu-latest

    steps:

      - name: Check out repository code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'

      - name: Publish alpha
        if: endswith(github.ref_name, '-alpha')
        run: npm publish --access public --tag alpha
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish beta
        if: endswith(github.ref_name, '-beta')
        run: npm publish --access public --tag beta
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Publish latest
        if:  ( !endswith(github.ref_name, '-beta') && !endswith(github.ref_name, '-alpha'))
        run: npm publish --access public --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
